export const SEASON_LABELS = [
  { key: "Futari wa Pretty Cure", label: "ふたりはプリキュア" },
  { key: "Futari wa Pretty Cure Max Heart", label: "ふたりはプリキュア Max Heart" },
  { key: "Futari wa Pretty Cure Splash Star", label: "ふたりはプリキュア Splash Star" },
  { key: "Yes! Pretty Cure 5", label: "Yes！プリキュア5" },
  { key: "Yes! Pretty Cure 5 GoGo!", label: "Yes！プリキュア5 GoGo！" },
  { key: "Fresh Pretty Cure!", label: "フレッシュプリキュア！" },
  { key: "Heartcatch Pretty Cure!", label: "ハートキャッチプリキュア！" },
  { key: "Suite Pretty Cure♪", label: "スイートプリキュア♪" },
  { key: "Smile Pretty Cure!", label: "スマイルプリキュア！" },
  { key: "DokiDoki! Pretty Cure", label: "ドキドキ！プリキュア" },
  { key: "HappinessCharge Pretty Cure!", label: "ハピネスチャージプリキュア！" },
  { key: "Go! Princess Pretty Cure", label: "Go！プリンセスプリキュア" },
  { key: "KiraKira☆Pretty Cure A La Mode", label: "キラキラ☆プリキュアアラモード" },
  { key: "Hugtto! Pretty Cure", label: "HUGっと！プリキュア" },
  { key: "Star☆Twinkle Pretty Cure", label: "スター☆トゥインクルプリキュア" },
  { key: "Healin' Good♥Pretty Cure", label: "ヒーリングっど♥プリキュア" },
  { key: "Tropical-Rouge! Pretty Cure", label: "トロピカル〜ジュ！プリキュア" },
  { key: "Delicious Party♡Pretty Cure", label: "デリシャスパーティ♡プリキュア" },
  { key: "Hirogaru Sky! Pretty Cure", label: "ひろがるスカイ！プリキュア" },
  { key: "Wonderful Pretty Cure!", label: "わんだふるぷりきゅあ！" },
  { key: "Kimi to Idol Pretty Cure♪", label: "キミとアイドルプリキュア♪" },
];
